install: lint
	go install ./...

lint:
	go vet ./...
	golangci-lint run ./...
	golint ./...

format:
	go fmt ./...
	git ls-files | grep '.*.go$$' | xargs goimports -d -w
	git ls-files | grep '.*.go$$' | xargs gofumpt -d -w
