install: lint
	go install ./...

debug_install: lint
	go install -gcflags="-m -m" -race ./...

lint:
	go vet ./...
	golangci-lint run --enable-all ./...
	golint ./...

format:
	go fmt ./...
	git ls-files | grep '.*.go$$' | xargs goimports -d -w
	git ls-files | grep '.*.go$$' | xargs gofumpt -d -w
